### ISSUE TITLE
Update README to standard format

### ISSUE THREAD

**Issue by aw1203** [uoy-trials/.github#15]
All repos need their README updating to the standard format.

Wiki age for standard format is here: https://uoy.atlassian.net/wiki/spaces/SEDP/pages/38076640/README.md+standard+format

Ownership Rating: 4

Quality Rating: 5

Specific Notes: None.

**Comment by jsk505** [comment]
expiry date - 3m after folowup end. or indefinite
review date: 30/4/2025
